@startuml

title __ADAPTERS's Class Diagram__\n

  namespace com.example.runder {
    namespace Adapters.Adapters {
      class com.example.runder.Adapters.Adapters.ChoosingGroupAdapter {
          - age : String
          - cb : HaveOrHaventGroupCB
          - context : Context
          - listener : SelectListener
          - listenerGroup : HaveOrHaventGroupCB
          - max_D : String
          - max_S : int
          + ChoosingGroupAdapter()
          + getItemCount()
          + onCreateViewHolder()
          # onBindViewHolder()
      }
    }
  }
  

  namespace com.example.runder {
    namespace Adapters.Adapters {
      class com.example.runder.Adapters.Adapters.ChoosingGroupAdapter.myViewHolder {
          ~ age : TextView
          ~ cardView : ConstraintLayout
          ~ distance : TextView
          ~ img : CircleImageView
          ~ linearLayoutCompat : LinearLayoutCompat
          ~ location : TextView
          ~ name : TextView
          ~ speed : TextView
          ~ status : TextView
          + myViewHolder()
      }
    }
  }
  

  namespace com.example.runder {
    namespace Adapters.Adapters {
      class com.example.runder.Adapters.Adapters.CommunityAdapter {
          + CommunityAdapter()
          + onCreateViewHolder()
          # onBindViewHolder()
      }
    }
  }
  

  namespace com.example.runder {
    namespace Adapters.Adapters {
      class com.example.runder.Adapters.Adapters.CommunityAdapter.myViewHolder {
          ~ address : TextView
          ~ birthDate : TextView
          ~ gender : TextView
          ~ imageView : CircleImageView
          ~ name : TextView
          + myViewHolder()
      }
    }
  }
  

  namespace com.example.runder {
    namespace Adapters.Adapters {
      class com.example.runder.Adapters.Adapters.GoogleSignUpAdapter {
          - context : Context
          + GoogleSignUpAdapter()
          + getItemCount()
          + getItemViewType()
          + onBindViewHolder()
          + onCreateViewHolder()
      }
    }
  }
  

  namespace com.example.runder {
    namespace Adapters.Adapters {
      class com.example.runder.Adapters.Adapters.IWantRunAdapter {
          + getItemCount()
          + getItemViewType()
          + onBindViewHolder()
          + onCreateViewHolder()
      }
    }
  }
  

  namespace com.example.runder {
    namespace Adapters.Adapters {
      class com.example.runder.Adapters.Adapters.ManagingGroupAdapter {
          - context : Context
          - currentTeam : String
          + ManagingGroupAdapter()
          + onCreateViewHolder()
          # onBindViewHolder()
      }
    }
  }
  

  namespace com.example.runder {
    namespace Adapters.Adapters {
      class com.example.runder.Adapters.Adapters.ManagingGroupAdapter.myViewHolder {
          ~ Age : TextView
          ~ Email : TextView
          ~ address : TextView
          ~ birthDate : TextView
          ~ constraintLayout : ConstraintLayout
          ~ gender : TextView
          ~ imageView : CircleImageView
          ~ name : TextView
          + myViewHolder()
      }
    }
  }
  

  namespace com.example.runder {
    namespace Adapters.Adapters {
      class com.example.runder.Adapters.Adapters.MyDetailsAdapter {
          ~ context : Context
          + MyDetailsAdapter()
          + onCreateViewHolder()
          # onBindViewHolder()
      }
    }
  }
  

  namespace com.example.runder {
    namespace Adapters.Adapters {
      class com.example.runder.Adapters.Adapters.MyDetailsAdapter.myViewHolder {
          ~ address : TextView
          ~ birthDate : TextView
          ~ gender : TextView
          ~ imageView : CircleImageView
          ~ name : TextView
          + myViewHolder()
      }
    }
  }
  

  namespace com.example.runder {
    namespace Adapters.Adapters {
      class com.example.runder.Adapters.Adapters.RegularSignUpAdapter {
          + getItemCount()
          + getItemViewType()
          + onBindViewHolder()
          + onCreateViewHolder()
      }
    }
  }
  

  com.example.runder.Adapters.Adapters.ChoosingGroupAdapter +-down- com.example.runder.Adapters.Adapters.ChoosingGroupAdapter.myViewHolder
  com.example.runder.Adapters.Adapters.CommunityAdapter +-down- com.example.runder.Adapters.Adapters.CommunityAdapter.myViewHolder
  com.example.runder.Adapters.Adapters.ManagingGroupAdapter +-down- com.example.runder.Adapters.Adapters.ManagingGroupAdapter.myViewHolder
  com.example.runder.Adapters.Adapters.MyDetailsAdapter +-down- com.example.runder.Adapters.Adapters.MyDetailsAdapter.myViewHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
